myproject/cart/urls.py
from django.urls import path
from .views import CreatePaymentIntentView, CartView, ProductListCreateView, ProductRetrieveUpdateDestroyView, UpdateOrderStatusView, ConfirmPaymentView, OrderHistoryView, OrderDeleteView \
    , PageViewTrackingView, OnlineUsersView

from webhooks.stripe_webhook import stripe_webhook

app_name = 'cart'

urlpatterns = [
    path('create-payment-intent/', CreatePaymentIntentView.as_view(), name='create-payment-intent'),
    path('cart/', CartView.as_view(), name='cart'),

    path('products/', ProductListCreateView.as_view(), name='product-list-create'),
    path('products/<int:pk>/', ProductRetrieveUpdateDestroyView.as_view(), name='product-retrieve-update-destroy'),

    path('stripe/webhook/', stripe_webhook, name='stripe-webhook'),

    path('orders/<int:order_id>/update-status', UpdateOrderStatusView.as_view(), name='update-order-status'),
    path('payment/confirm/', ConfirmPaymentView.as_view(), name='confirm_payment'),

    path('orders/', OrderHistoryView.as_view(), name='order_history'),
    path('order/<int:order_id>/delete/', OrderDeleteView.as_view(), name='order_delete'),

    path('track-page-view/', PageViewTrackingView.as_view(), name='track_page_view'),

    path('online-users/', OnlineUsersView.as_view(), name='online_users'),

]

myproject/myproject/urls.py
from myproject import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from webhooks.sentry_webhook import sentry_error_webhook
from graphene_django.views import GraphQLView
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path('silk/', include('silk.urls', namespace='silk')),
    path("admin/", admin.site.urls),
    path('users/', include('users.urls', namespace='users')),#'users:login' #namespace is the same as # app_name= 'users', if there are the same names of urls in different apps then it wont be confused
    path('cart/', include('cart.urls', namespace='cart')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('api/sentry-error/', sentry_error_webhook, name='sentry-error-webhook'),
    path("graphql/", csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

if settings.DEBUG: # setting the address to display uploaded picture on the page
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # Serve static files

myproject/users/urls.py
from django.urls import path, reverse_lazy
from .views import RegisterUser, LogoutView, ProfileUser, UserPasswordChange, \
      CustomTokenObtainPairView, UserListView, UserDetailView, \
      SubscriptionPlanListView, SubscribeView, SubscriptionStatusView



from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetDoneView, \
    PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView

from rest_framework_simplejwt.views import  TokenRefreshView 

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),

    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),


    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),#the views are built-in, but templates are our own, slightly customized, url names should be exactly the same
    path('password-reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                                             success_url=reverse_lazy('users:password_reset_complete')),name='password_reset_confirm'),        
    path('password-reset/complete/',PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),

    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', ProfileUser.as_view(), name='profile'),
    path('users/', UserListView.as_view(), name='user-list'),                                                                                                    
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-list'), 

    #subscriptions
    path('plans/', SubscriptionPlanListView.as_view(), name='subscription-plans'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('status/', SubscriptionStatusView.as_view(), name='subscription-status'),
    

]

myproject/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm




class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='login', 
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='password',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']



class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='repeat password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
        labels = {
            'email': 'e-mail',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'})
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('email already exists')
        return email
    

class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='email', widget=forms.TextInput(attrs={'class': 'form-input'}))

    this_year = datetime.date.today().year
    data_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year-100, this_year-5))))


    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'data_birth', 'email']



class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label='New password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

myproject/users/views.py
from django.urls import reverse, reverse_lazy
from django.contrib.auth import  login, logout, get_user_model
from django.http import  HttpResponseRedirect
from myproject import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.permissions import IsAuthenticated
from .serializers import LoginSerializer, RegisterSerializer, ProfileSerializer, PasswordChangeSerializer, UserSerializer
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework_simplejwt.tokens import RefreshToken  
from rest_framework_simplejwt.views import TokenObtainPairView
from .serializers import CustomTokenObtainPairSerializer
from rest_framework_simplejwt.exceptions import TokenError
from rest_framework.permissions import AllowAny
from rest_framework.generics import RetrieveDestroyAPIView
from .models import Subscription, SubscriptionPlan
from django.utils import timezone 
from datetime import timedelta
from .serializers import SubscriptionSerializer, SubscriptionPlanSerializer
# login view 
class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer


class UserDetailView(RetrieveDestroyAPIView):
    """
    Retrieve or delete a specific user by ID.
    """
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer

    def delete(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.delete()
        return Response({"message": "User deleted successfully"}, status=status.HTTP_204_NO_CONTENT)


# class LoginUser(APIView):  # Change to APIView for API handling
#     def post(self, request):
#         serializer = LoginSerializer(data=request.data)
#         if serializer.is_valid():
#             user = serializer.validated_data['user']
#             login(request, user)
#             # You can return user data or a token here
#             photo_url = None
#             if user.photo:
#                 photo_url = f"{request.build_absolute_uri(settings.MEDIA_URL)}{user.photo.name}"

#             return Response({
#                 "message": "Login successful",
#                 "username": user.username,
#                 "photo": photo_url  # Return the photo URL or None if not set
#             }, status=status.HTTP_200_OK)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    
#     def get(self, request):
#         # You can return a simple message or a form if needed
#         return Response({"message": "Please provide your username and password to log in."}, status=status.HTTP_200_OK)


# @api_view(['POST'])
# def logout_user(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('users:login'))


from django.core.cache import caches
import logging
logger = logging.getLogger(__name__)
ONLINE_USERS_KEY = "online_users"
class LogoutView(APIView):
    permission_classes = [AllowAny]  # No authentication required

    def post(self, request):
        refresh_token = request.data.get('refresh_token')
        if not refresh_token:
            return Response({"detail": "Refresh token is required"}, status=status.HTTP_400_BAD_REQUEST)

        try:
            token = RefreshToken(refresh_token)
            token.blacklist()

            # Remove user from online status
            user_id = request.user.id

            logger.info(f"User {user_id} IDENTIFIED")
            cache = caches['page_view_cache']

            if user_id:
                cache.delete(f'{ONLINE_USERS_KEY}:{user_id}')
                logger.info(f"User {user_id} removed from online users.")

            return Response({"detail": "Successfully logged out"}, status=status.HTTP_205_RESET_CONTENT)
        except TokenError:
            return Response({"detail": "Invalid or already blacklisted token"}, status=status.HTTP_400_BAD_REQUEST)
        except Exception as e:
            return Response({"detail": str(e)}, status=status.HTTP_400_BAD_REQUEST)


class RegisterUser(APIView):
    def post(self, request):
        serializer = RegisterSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save() 
        refresh = RefreshToken.for_user(user)
        access = refresh.access_token

        return Response({
            "access": str(access),
            "refresh": str(refresh),
            "user": {
                "username": user.username,
                "photo": user.photo.url if user.photo else None, 
                "is_admin": user.is_staff,
                "is_premium": user.is_premium
            }
        }, status=status.HTTP_201_CREATED)
    
class ProfileUser(LoginRequiredMixin, generics.UpdateAPIView):
    
    serializer_class = ProfileSerializer
    queryset = get_user_model().objects.all() #probably returns all the users, 


    def get_object(self, queryset=None):
        return self.request.user # updates the logged in user profile
    

class UserListView(generics.ListAPIView):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer


class UserPasswordChange(LoginRequiredMixin, generics.UpdateAPIView):
    # form_class = UserPasswordChangeForm
    # success_url = reverse_lazy('users:password_change_done')
    # template_name = 'users/password_change_form.html'

    serializer_class = PasswordChangeSerializer

    def get_object(self):
        return self.request.user #changes the password for the logged in user
    

    def perform_update(self, serializer):
        serializer.save()  #calls the save method to change the password


class SubscriptionPlanListView(generics.ListAPIView):
    """Returns a list of available subscription plans from the database."""
    queryset = SubscriptionPlan.objects.all()
    serializer_class = SubscriptionPlanSerializer

class SubscribeView(generics.GenericAPIView):
    """Allows the user to subscribe to a plan."""
    # permission_classes = [IsAuthenticated]
    serializer_class = SubscriptionSerializer

    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return Response({'error': 'You must be logged in to subscribe'}, status=status.HTTP_401_UNAUTHORIZED)

        try:
            subscription = Subscription.objects.get(user=user)
            if subscription.is_active():
                return Response({'error': 'You already have an active subscription'}, status=status.HTTP_400_BAD_REQUEST)
        except Subscription.DoesNotExist:
            pass

        plan_id = request.data.get('plan')

        if not plan_id:
            return Response({'error': 'Plan is required'}, status=status.HTTP_400_BAD_REQUEST)

       
        try:
            plan_id = int(plan_id)
            plan = SubscriptionPlan.objects.get(id=plan_id)
        except ValueError:
            return Response({'error': 'Invalid plan ID'}, status=status.HTTP_400_BAD_REQUEST)
        except SubscriptionPlan.DoesNotExist:
            return Response({'error': 'Plan not found'}, status=status.HTTP_404_NOT_FOUND)

        subscription, created = Subscription.objects.get_or_create(
            user=user,
            defaults={
                'plan': plan,
                'start_date': timezone.now(),
                'end_date': timezone.now() + timedelta(days=30), #1 month subscription
                'active': True
            }
            )
        if not created:
            subscription.plan = plan
            subscription.start_date = timezone.now()
            subscription.end_date = timezone.now() + timedelta(days=30)
            subscription.active = True
            subscription.save()

        return Response({'message': f'Subscribed to {plan.name} plan'}, status=status.HTTP_200_OK)
        

class SubscriptionStatusView(generics.RetrieveAPIView):
    """Returns the current subscription status of the authenticated user."""
    # permission_classes = [IsAuthenticated]


    def get(self, request):
        user = request.user
        try:
            subscription = Subscription.objects.get(user=user)
            subscription.is_active()
            return Response({
                'plan': subscription.plan.name,
                'active': subscription.active,
                'start_date': subscription.start_date,
                'end_date': subscription.end_date
            }, status=200)
        except Subscription.DoesNotExist:
            return Response({
                            'plan': None,
                            'active': False
                        }, status=200)         


# @api_view(['POST'])
# def subscrite_to_plan(request):
#     user = request.user
#     plan_id = request.data.get('plan')

#     if not user.is_authenticated:
#         return Response({'error': 'Authentication required'}, status=status.HTTP_401_UNAUTHORIZED)

#     try:
#         plan = SubscriptionPlan.objects.get(id=plan_id)
#         #check if the user has alredy got a subscription
#         subscription, created = Subscription.objects.get_or_create(user=user)
#         subscription.plan = plan
#         subscription.start_date = timezone.now()
#         subscription.end_date = timezone.now() + timedelta(days=30)
#         subscription.active = True
#         subscription.save()
#         return Response({'message': 'Subscribed successfully'}, status=status.HTTP_200_OK)
#     except SubscriptionPlan.DoesNotExist:
#         return Response({'error': 'Plan not found'}, status=status.HTTP_404_NOT_FOUND)

myproject/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>authorization</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <!-- <input type="hidden" name="next" value="{{ next }}" />  helps to redirect to a certain page after logging in/ doesnt work for some reason. even though in the url everything is correct-->
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %} <!-- form.title is replaced by f, form.slug the same/ iterates through each field taken from model Men: title, slug, content etc. -->
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p> <!-- here is class="form-label", however if we need to write our custom classes then we go to the forms and create attribute widget -->
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <!-- the block above(before csrf_token) was incerted instead of form.as_p( manually defined the form-->
    <p><button type="submit">login</button></p>

    <p><a href="{% url 'users:password_reset' %}">Forgot the password?</a></p>

</form>
{% endblock  %}

myproject/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Password has been successfully changed</h1>

<p>You have changed the password. <a href="{% url 'users:profile' %}">Go back to the profile</a></p>

{% endblock %}

myproject/templates/users/password_change_form.html
{% extends 'base.html' %}


{% block content %}

<h1>Change the password</h1>
<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %} <!-- form.title is replaced by f, form.slug the same/ iterates through each field taken from model Men: title, slug, content etc. -->
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p> <!-- here is class="form-label", however if we need to write our custom classes then we go to the forms and create attribute widget -->
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Change the password</button></p>
</form>

{% endblock %}

myproject/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Password has been changed</h1>

<p>You have successfully changed the password of your account. Use it to <a href="{% url 'users:login' %}">log in</a></p>

{% endblock %}

myproject/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>New password</h1>

<form method="post">
    {% csrf_token %}
    <!-- <input type="hidden" name="next" value="{{ next }}" />  helps to redirect to a certain page after logging in/ doesnt work for some reason. even though in the url everything is correct-->
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %} <!-- form.title is replaced by f, form.slug the same/ iterates through each field taken from model Men: title, slug, content etc. -->
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p> <!-- here is class="form-label", however if we need to write our custom classes then we go to the forms and create attribute widget -->
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <!-- the block above(before csrt_token) was incerted instead of form.as_p( manually defined the form-->
    <p><button type="submit">Save</button></p>


</form>
{% endblock  %}

myproject/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Reset the password</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

myproject/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

myproject/templates/users/password_reset_form.html
{% extends 'base.html' %}


{% block content %}

<h1>Regain the password</h1>

<form method="post">
    {% csrf_token %}

    {% for f in form %} <!-- form.title is replaced by f, form.slug the same/ iterates through each field taken from model Men: title, slug, content etc. -->
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p> <!-- here is class="form-label", however if we need to write our custom classes then we go to the forms and create attribute widget -->
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Reset the password</button></p>
</form>

{% endblock %}

myproject/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Profile</h1>

<form method="post" enctype="multipart/form-data"> <!-- after we added field photo to ProfileUserForm we have to add here 'enctype' to display photos -->

    {% csrf_token %}
    
<!--this block is to display photo of a user-->
    {% if user.photo %}
    <p><img src="{{ user.photo.url }}"></p>
    {% else %}
    <p><img src="{{ default_image }}"></p><!-- in extra_context in class ProfileUser -->
    {% endif %}
    
    
<div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %} <!-- form.title is replaced by f, form.slug the same/ iterates through each field taken from model Men: title, slug, content etc. -->
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p> <!-- here is class="form-label", however if we need to write our custom classes then we go to the forms and create attribute widget -->
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

        <p><button type="submit">Save</button></p>
</form>

<hr>
<p><a href="{% url 'users:password_change' %}">Change the password</a> </p>
{% endblock %}

myproject/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h1>Register</h1>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"/> <!-- hidden button, logged in the user to the desired page after logging in -->
<!--    {{ form.as_p }}-->
<!--instead of form.as_p we used cycle for to display form, then it looks prettier and more neat (all the fields are of the same length)-->
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %} <!-- form.title is replaced by f, form.slug the same/ iterates through each field taken from model Men: title, slug, content etc. -->
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p> <!-- here is class="form-label", however if we need to write our custom classes then we go to the forms and create attribute widget -->
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Register</button></p>

</form>

{% endblock %}

myproject/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome</h1>
<p>You have successfully been registered. To log in follow this
    <a href="{% url 'users:login' %}">link</a>
</p>


{% endblock %}